Program (1)
  ExtDefList (1)
    ExtDef (1)
      Specifier (1)
        TYPE: int
      FunDec (1)
        ID: main
        LP
        RP
      CompSt (1)
        LC
        DefList (2)
          Def (2)
            Specifier (2)
              TYPE: int
            DecList (2)
              Dec (2)
                VarDec (2)
                  ID: i
                ASSIGNOP
                Exp (2)
                  Exp (2)
                    INT: 122
                  STAR
                  Exp (2)
                    INT: 52
            SEMI
          DefList (3)
            Def (3)
              Specifier (3)
                TYPE: int
              DecList (3)
                Dec (3)
                  VarDec (3)
                    ID: j
                  ASSIGNOP
                  Exp (3)
                    Exp (3)
                      Exp (3)
                        ID: i
                      STAR
                      Exp (3)
                        ID: i
                    PLUS
                    Exp (3)
                      Exp (3)
                        INT: 182
                      DIV
                      Exp (3)
                        ID: i
              SEMI
            DefList (4)
              Def (4)
                Specifier (4)
                  TYPE: int
                DecList (4)
                  Dec (4)
                    VarDec (4)
                      ID: k
                    ASSIGNOP
                    Exp (4)
                      Exp (4)
                        INT: 211
                      PLUS
                      Exp (4)
                        ID: j
                SEMI
        RC
