Program (1)
  ExtDefList (1)
    ExtDef (1)
      Specifier (1)
        TYPE: int
      FunDec (1)
        ID: main
        LP
        RP
      CompSt (1)
        LC
        DefList (2)
          Def (2)
            Specifier (2)
              TYPE: float
            DecList (2)
              Dec (2)
                VarDec (2)
                  ID: f_1
                ASSIGNOP
                Exp (2)
                  FLOAT: 0.232342
            SEMI
          DefList (3)
            Def (3)
              Specifier (3)
                TYPE: float
              DecList (3)
                Dec (3)
                  VarDec (3)
                    ID: f_2
                  ASSIGNOP
                  Exp (3)
                    FLOAT: 0.000000
              SEMI
            DefList (4)
              Def (4)
                Specifier (4)
                  TYPE: float
                DecList (4)
                  Dec (4)
                    VarDec (4)
                      ID: f_3
                    ASSIGNOP
                    Exp (4)
                      Exp (4)
                        Exp (4)
                          ID: f_1
                        STAR
                        Exp (4)
                          ID: f_2
                      MINUS
                      Exp (4)
                        ID: f_1
                SEMI
        StmtList (5)
          Stmt (5)
            Exp (5)
              Exp (5)
                ID: f_1
              ASSIGNOP
              Exp (5)
                Exp (5)
                  ID: f_1
                STAR
                Exp (5)
                  FLOAT: 0.000000
            SEMI
        RC
