Program (1)
  ExtDefList (1)
    ExtDef (1)
      Specifier (1)
        TYPE: float
      FunDec (1)
        ID: fo
        LP
        RP
      CompSt (1)
        LC
        DefList (2)
          Def (2)
            Specifier (2)
              TYPE: float
            DecList (2)
              Dec (2)
                VarDec (2)
                  ID: f1
                ASSIGNOP
                Exp (2)
                  Exp (2)
                    ID: e1
                  DOT
                  ID: e1
            SEMI
          DefList (3)
            Def (3)
              Specifier (3)
                TYPE: float
              DecList (3)
                Dec (3)
                  VarDec (3)
                    ID: f2
                  ASSIGNOP
                  Exp (3)
                    MINUS
                    Exp (3)
                      FLOAT: 2130.000000
              SEMI
        StmtList (4)
          Stmt (4)
            Exp (4)
              Exp (4)
                ID: f1
              ASSIGNOP
              Exp (4)
                Exp (4)
                  ID: f1
                DIV
                Exp (4)
                  FLOAT: 1.000000
            SEMI
          StmtList (5)
            Stmt (5)
              Exp (5)
                Exp (5)
                  ID: f2
                ASSIGNOP
                Exp (5)
                  Exp (5)
                    Exp (5)
                      ID: f1
                    STAR
                    Exp (5)
                      FLOAT: 21332.000000
                  MINUS
                  Exp (5)
                    LP
                    Exp (5)
                      Exp (5)
                        FLOAT: 1.000000
                      MINUS
                      Exp (5)
                        FLOAT: 10.000000
                    RP
              SEMI
        RC
