Program (8)
  ExtDefList (8)
    ExtDef (8)
      Specifier (8)
        TYPE: int
      FunDec (8)
        ID: l_strcmp
        LP
        VarList (8)
          ParamDec (8)
            Specifier (8)
              StructSpecifier (8)
                STRUCT
                Tag (8)
                  ID: TString
            VarDec (8)
              ID: ls
          COMMA
          VarList (8)
            ParamDec (8)
              Specifier (8)
                StructSpecifier (8)
                  STRUCT
                  Tag (8)
                    ID: TString
              VarDec (8)
                ID: rs
        RP
      CompSt (8)
        LC
        DefList (9)
          Def (9)
            Specifier (9)
              TYPE: int
            DecList (9)
              Dec (9)
                VarDec (9)
                  ID: l
                ASSIGNOP
                Exp (9)
                  ID: getstr
                  LP
                  Args (9)
                    Exp (9)
                      ID: ls
                  RP
            SEMI
          DefList (10)
            Def (10)
              Specifier (10)
                TYPE: int
              DecList (10)
                Dec (10)
                  VarDec (10)
                    ID: ll
                  ASSIGNOP
                  Exp (10)
                    ID: tsslen
                    LP
                    Args (10)
                      Exp (10)
                        ID: ls
                    RP
              SEMI
            DefList (11)
              Def (11)
                Specifier (11)
                  TYPE: int
                DecList (11)
                  Dec (11)
                    VarDec (11)
                      ID: r
                    ASSIGNOP
                    Exp (11)
                      ID: getstr
                      LP
                      Args (11)
                        Exp (11)
                          ID: rs
                      RP
                SEMI
              DefList (12)
                Def (12)
                  Specifier (12)
                    TYPE: int
                  DecList (12)
                    Dec (12)
                      VarDec (12)
                        ID: lr
                      ASSIGNOP
                      Exp (12)
                        ID: tsslen
                        LP
                        Args (12)
                          Exp (12)
                            ID: rs
                        RP
                  SEMI
        StmtList (13)
          Stmt (13)
            WHILE
            LP
            Exp (13)
              INT: 1
            RP
            Stmt (13)
              CompSt (13)
                LC
                DefList (14)
                  Def (14)
                    Specifier (14)
                      TYPE: int
                    DecList (14)
                      Dec (14)
                        VarDec (14)
                          ID: temp
                        ASSIGNOP
                        Exp (14)
                          ID: strcoll
                          LP
                          Args (14)
                            Exp (14)
                              ID: l
                            COMMA
                            Args (14)
                              Exp (14)
                                ID: r
                          RP
                    SEMI
                StmtList (15)
                  Stmt (15)
                    IF
                    LP
                    Exp (15)
                      Exp (15)
                        ID: temp
                      RELOP
                      Exp (15)
                        INT: 0
                    RP
                    Stmt (16)
                      RETURN
                      Exp (16)
                        ID: temp
                      SEMI
                    ELSE
                    Stmt (17)
                      CompSt (17)
                        LC
                        DefList (18)
                          Def (18)
                            Specifier (18)
                              TYPE: int
                            DecList (18)
                              Dec (18)
                                VarDec (18)
                                  ID: len
                                ASSIGNOP
                                Exp (18)
                                  ID: strlen
                                  LP
                                  Args (18)
                                    Exp (18)
                                      ID: l
                                  RP
                            SEMI
                        StmtList (19)
                          Stmt (19)
                            IF
                            LP
                            Exp (19)
                              Exp (19)
                                ID: len
                              RELOP
                              Exp (19)
                                ID: lr
                            RP
                            Stmt (20)
                              RETURN
                              Exp (20)
                                Exp (20)
                                  Exp (20)
                                    LP
                                    Exp (20)
                                      Exp (20)
                                        ID: len
                                      RELOP
                                      Exp (20)
                                        ID: ll
                                    RP
                                  MINUS
                                  Exp (20)
                                    INT: 0
                                PLUS
                                Exp (20)
                                  INT: 1
                              SEMI
                            ELSE
                            Stmt (21)
                              IF
                              LP
                              Exp (21)
                                Exp (21)
                                  ID: len
                                RELOP
                                Exp (21)
                                  ID: ll
                              RP
                              Stmt (22)
                                RETURN
                                Exp (22)
                                  MINUS
                                  Exp (22)
                                    INT: 1
                                SEMI
                          StmtList (24)
                            Stmt (24)
                              Exp (24)
                                Exp (24)
                                  ID: len
                                ASSIGNOP
                                Exp (24)
                                  Exp (24)
                                    ID: len
                                  PLUS
                                  Exp (24)
                                    INT: 1
                              SEMI
                            StmtList (25)
                              Stmt (25)
                                Exp (25)
                                  Exp (25)
                                    ID: l
                                  ASSIGNOP
                                  Exp (25)
                                    Exp (25)
                                      ID: l
                                    PLUS
                                    Exp (25)
                                      ID: len
                                SEMI
                              StmtList (25)
                                Stmt (25)
                                  Exp (25)
                                    Exp (25)
                                      ID: ll
                                    ASSIGNOP
                                    Exp (25)
                                      Exp (25)
                                        ID: ll
                                      MINUS
                                      Exp (25)
                                        ID: len
                                  SEMI
                                StmtList (25)
                                  Stmt (25)
                                    Exp (25)
                                      Exp (25)
                                        ID: r
                                      ASSIGNOP
                                      Exp (25)
                                        Exp (25)
                                          ID: r
                                        PLUS
                                        Exp (25)
                                          ID: len
                                    SEMI
                                  StmtList (25)
                                    Stmt (25)
                                      Exp (25)
                                        Exp (25)
                                          ID: lr
                                        ASSIGNOP
                                        Exp (25)
                                          Exp (25)
                                            ID: lr
                                          MINUS
                                          Exp (25)
                                            ID: len
                                      SEMI
                        RC
                RC
        RC
    ExtDefList (35)
      ExtDef (35)
        Specifier (35)
          TYPE: int
        FunDec (35)
          ID: foo
          LP
          RP
        CompSt (35)
          LC
          DefList (36)
            Def (36)
              Specifier (36)
                TYPE: int
              DecList (36)
                Dec (36)
                  VarDec (36)
                    ID: a
                  ASSIGNOP
                  Exp (39)
                    INT: 323
              SEMI
            DefList (40)
              Def (40)
                Specifier (40)
                  TYPE: int
                DecList (41)
                  Dec (41)
                    VarDec (41)
                      ID: b
                    ASSIGNOP
                    Exp (41)
                      MINUS
                      Exp (41)
                        MINUS
                        Exp (41)
                          MINUS
                          Exp (41)
                            MINUS
                            Exp (41)
                              INT: 1
                SEMI
          RC
